# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_invitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="send_count",
        ),
    ]
