# Generated by Django 6.0.7 on 2026-08-18 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_invitation_send_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_pending_tenant_invitation',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='tenants_inv_user_id_idx',
        ),
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tenant_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status'], name='tenants_inv_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant', 'email'), name='unique_pending_tenant_invitation'),
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
    ]
